#!/bin/sh

function start() {
	echo "Starting the TypeScript watcher"
	tsc --watch >tsc.out.log 2>tsc.err.log &
	echo $! > tsc.pid
	echo "Starting the Middleman server"
	bundle exec middleman serve >mid.out.log 2>mid.err.log &
	echo $! > mid.pid
}

function stop() {
	echo "Stopping the Middleman server"
	kill $(cat mid.pid)
	rm mid.pid
	echo "Stopping the TypeScript watcher"
	kill $(cat tsc.pid)
	rm tsc.pid
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	*)
		echo "Use start to turn on the servers or stop to stop them."
	;;
esac
